# Generated by Django 6.0.1 on 2026-01-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_producto_foto_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('QR', 'QR')], default='Efectivo', max_length=20),
        ),
    ]
