# Generated by Django 6.0.1 on 2026-01-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_venta_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='numero_rol',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
