# Generated by Django 6.0.1 on 2026-01-12 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rol_numero_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.sucursal'),
            preserve_default=False,
        ),
    ]
