# Generated by Django - Data Migration for Initial Roles and Sucursales

from django.db import migrations


def create_initial_data(apps, schema_editor):
    """
    Crea los datos iniciales necesarios para el sistema:
    - Roles con numero_rol definido
    - Sucursal principal
    """
    Rol = apps.get_model('api', 'Rol')
    Sucursal = apps.get_model('api', 'Sucursal')

    # Crear Roles solo si no existen
    if not Rol.objects.exists():
        Rol.objects.create(nombre_rol="Super Administrador", numero_rol=1)
        Rol.objects.create(nombre_rol="Administrador", numero_rol=2)
        Rol.objects.create(nombre_rol="Técnico", numero_rol=3)
        Rol.objects.create(nombre_rol="Cajero", numero_rol=4)
        Rol.objects.create(nombre_rol="Técnico y Cajero", numero_rol=5)
        print("✅ Roles iniciales creados")

    # Crear Sucursal principal solo si no existe
    if not Sucursal.objects.exists():
        Sucursal.objects.create(
            nombre="Sucursal Central",
            direccion="Oficina Matriz",
            activo=True
        )
        print("✅ Sucursal principal creada")


def reverse_initial_data(apps, schema_editor):
    """
    Revertir la migración (opcional, borra los datos)
    """
    Rol = apps.get_model('api', 'Rol')
    Sucursal = apps.get_model('api', 'Sucursal')
    
    # Eliminar datos creados (cuidado en producción)
    Rol.objects.filter(numero_rol__in=[1, 2, 3, 4, 5]).delete()
    Sucursal.objects.filter(nombre="Sucursal Central").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_venta_id_sucursal'),  # Última migración existente
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]
