# Generated by Django 6.0.1 on 2026-01-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('Completada', 'Completada'), ('Anulada', 'Anulada')], default='Completada', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
