# Generated by Django 6.0.1 on 2026-01-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_venta_estado_venta_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciotecnico',
            name='costo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='marca_dispositivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='modelo_dispositivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
