# Generated by Django 6.0.1 on 2026-01-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_serviciotecnico_costo_estimado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciotecnico',
            name='telefono_contacto',
        ),
    ]
