# Generated by Django 6.0.1 on 2026-01-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_serviciotecnico_telefono_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='estado',
            field=models.CharField(choices=[('En Reparación', 'En Reparación'), ('Para Retirar', 'Para Retirar'), ('Entregado', 'Entregado'), ('Anulado', 'Anulado')], default='En Reparación', max_length=20),
        ),
    ]
