# Generated by Django 6.0.1 on 2026-01-19 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciotecnico',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='id_tecnico_asignado',
            field=models.ForeignKey(blank=True, db_column='id_tecnico_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
