# Generated by Django 6.0.1 on 2026-01-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_serviciotecnico_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='otro_numero_celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
