# Generated by Django 6.0.1 on 2026-01-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cliente_otro_numero_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='numero_cel1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='numero_cel2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
