# Generated by Django 6.0.1 on 2026-01-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sucursal_numero_cel1_sucursal_numero_cel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciotecnico',
            name='adelanto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
