# Generated by Django 6.0.1 on 2026-01-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_serviciotecnico_adelanto_serviciotecnico_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciotecnico',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
