# Generated by Django 6.0.1 on 2026-02-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_producto_precio_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo del producto al momento de la venta', max_digits=10),
        ),
    ]
